[project]
name = "mcp-cloud"
version = "0.1.0"
description = "MCP Server based on Anthropic's Model Context Protocol"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.6.0",
]
